[tool.commitizen]
name = "cz_conventional_commits"
version = "0.10.2"
version_files = [
    "Cargo.toml:^version",
    "crates/schematools/src/lib.rs:const VERSION"
]
bump_message = "chore: bump version $current_version â†’ $new_version [skip-ci]"
tag_format = "v$version"
