[tool.commitizen]
name = "cz_conventional_commits"
version = "0.17.1"
version_files = [
    "Cargo.toml:^version",
    "crates/schematools/src/lib.rs:const VERSION",
    "crates/cli/Cargo.toml:^schematools",
]
bump_message = "chore: bump version $current_version â†’ $new_version [skip-ci]"
tag_format = "v$version"
