[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
version_files = [
    "cargo.toml:^version",
    "src/main.rs:const VERSION"
]
bump_message = "chore: bump version $current_version â†’ $new_version [skip-ci]"
tag_format = "v$version"